# Generated by Django 6.1 on 2026-09-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_rbac_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareComponent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_id', models.IntegerField()),
                ('component_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_management"."hardware_components',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_id', models.IntegerField()),
                ('load_average', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('memory_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disk_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uptime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_management"."health_checks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server_id', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_management"."maintenance_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('server_id', models.IntegerField()),
                ('interface_name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('network_type', models.CharField(blank=True, max_length=50, null=True)),
                ('speed_mbps', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'server_management"."network_interfaces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu', models.CharField(blank=True, max_length=100, null=True)),
                ('ram_gb', models.IntegerField(blank=True, null=True)),
                ('storage_gb', models.IntegerField(blank=True, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('motherboard', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'server_management"."server_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'name'],
            },
        ),
    ]
