name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: applications/go_agent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: applications/go_agent/go.mod
          cache-dependency-path: applications/go_agent/go.sum

      - name: Show Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Build Go applications
        run: go build ./...
